import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';

export default defineConfig({
  integrations: [mdx()],
  output: 'static',
  trailingSlash: 'always',

  // ── Static path redirects from the old site ──────────────────────────────
  // Add an entry here whenever a new page replaces a known old-site URL.
  // Note: query-string redirects (?cid=N, ?filename=...) are handled by
  // worker.js (generated by scripts/generate-redirects.mjs), not here.
  redirects: {
    // Arbour Report
    '/resources/arbour_report/arbour_rpt.htm': '/resources/arbour-report/',
  },
});
